---
title: "Run Expectancy App"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)
options(shiny.trace = FALSE)
```

```{r Lodaing Packages, echo=FALSE}
library(tidyverse)
library(shiny)
library(plotly)
```

```{r Importing Data, echo=FALSE}
df1 <- read_csv(here::here('~/STA 518/STA518_Project/Results/Seaon Total Innings.csv'))
```

```{r combine runners, echo=FALSE}
df <- df1 %>% 
  unite(Onbase, First:Third) %>% 
  mutate(`top_bot` = case_when(`Home Team` ==0 ~ "Top",
                               `Home Team` ==1 ~ "Bottom"),
         runners = case_when(Onbase == '0_0_0' ~ "No Runners",
                             Onbase == '1_0_0' ~ "First",
                             Onbase == '1_1_0' ~ "First and Second",
                             Onbase == '1_0_1' ~ "First and Third",
                             Onbase == '0_1_0' ~ "Second",
                             Onbase == '0_1_1' ~ "Second and Third",
                             Onbase == '0_0_1' ~ "Third",
                             Onbase == '1_1_1' ~ "Bases Loaded"))

```

```{r formating df1, ecHo=FALSE}
df1 <- df1 %>% 
  mutate(`Scored` = if_else(`Inning Runs` >= 1,TRUE,FALSE))


df_group <- df1 %>% 
  group_by(First, Second, Third, Outs) %>% 
  summarise(Runs = sum(`Inning Runs`),
         Occurences = n(),
         `Probabilty of Scoring` = mean(Scored))
    
df_group <- df_group %>%  
  mutate(`Runs Expected` = Runs/Occurences) %>% 
  unite(Onbase, First:Third) 

runs_expected_matrix <- df_group %>% 
  pivot_wider(id_cols=Onbase, names_from=Outs, values_from=`Runs Expected`, names_prefix='Outs: ', names_sep=' ') %>% 
  arrange(desc('Outs: 0'))
  

run_prob_matrix <- df_group %>% 
  pivot_wider(id_cols=Onbase, names_from=Outs, values_from=`Probabilty of Scoring`, names_prefix='Outs: ', names_sep=' ')

```


```{r Run_inputs, echo=FALSE}
ui <- fluidPage(
  theme = bslib::bs_theme(bootswatch = "flatly"),
  titlePanel(
    "Run Expectancy"
  ),
  
  sidebarLayout(
    
    sidebarPanel(
      "Selections",
  sliderInput("n_inning", label = "Inning:",
              min = 1, max = 9, value = 1, step = 1),
  
  radioButtons("top_or_bot", label = "Top or Bottom of Inning:",
              choices = c('Top', 'Bottom')),
  
  radioButtons("n_outs", label = "Number of Outs:",
              choices = c(0, 1, 2)),
  
  selectInput("base_runners", label = "Base Runners:",
              choices = c('No Runners','First', 'Second', 'Third', 'First and Second',
                          'First and Third', 'Second and Third', 'Bases Loaded'), selected = "No Runners")
    ),
  
  mainPanel(
      plotOutput("plot")
      # tabPanel(tableOutput("static"))
    )
  )
)


server <- function(input, output, session){
  output$panel <- renderText({
    paste("Current panel: ", input$tabset)
  })
  
  output$static <- renderTable(head(df %>% 
    filter(
      #(Inning == input$n_inning) &
           (top_bot == input$top_or_bot) &
           (Outs == input$n_outs) &
           (runners == input$base_runners)) %>%
    select(`Inning Runs`)))

  output$plot <- renderPlot(
    ggplot(
      df %>% 
        filter(
          (Inning == input$n_inning) &
             (top_bot == input$top_or_bot) &
             (Outs == input$n_outs) &
             (runners == input$base_runners)) %>%
        select(`Inning Runs`),
      aes(x=`Inning Runs`)) +
      geom_histogram() +
      geom_density()
  )
}



```

```{r running shiny function, echo=FALSE}
shinyApp(ui, server)
```


```{r Runs Expected Matrix}
p <- df_group %>% 
  ggplot(aes(y=Onbase, fill=`Runs Expected`, x=Outs))+
  geom_tile()
ggplotly(p)

```


```{r Probability of Scoring Matrix}
p <- df_group %>% 
  ggplot(aes(y=Onbase, fill=`Probabilty of Scoring`, x=Outs))+
  geom_tile()
ggplotly(p)
```




